"use client";

import { useEffect, useMemo, useRef, useState } from "react";

type Anime={anime_id:number;title:string;description?:string;year?:number;season?:number;poster?:{big?:string;fullsize?:string};rating?:{average?:number};genres?:{title:string;alias:string}[];type?:{name?:string};views?:number;anime_status?:{value?:number;title?:string;alias?:string};franchiseCount?:number;franchiseEntries?:Anime[]};
type Video={video_id:number;iframe_url:string;number:string;duration?:number;data:{dubbing:string;player:string};skips?:{opening?:{time:number;length:number}|null;ending?:{time:number;length:number}|null}};
type EpisodeState={position:number;duration:number;percent:number;updatedAt:number;completed?:boolean};
type AnimeProgress={episode:string;dub:string;episodes:Record<string,EpisodeState>;totalEpisodes?:number;totalDuration?:number;season?:number};
type Progress=Record<number,AnimeProgress>;
type Folder={id:string;name:string;animeIds:number[];notes?:Record<number,string>};
type Tracker={animeId:number;animeIds?:number[];title:string;knownEpisodes:number;newEpisodes:number;dubs?:string[]};
type ToolbarPosition="top"|"bottom"|"left"|"right";
type PlayerPrefs={autoSkipOpening:boolean;autoSkipEnding:boolean;autoNext:boolean;autoPlayResume:boolean};
type CardMeta={familyCount:number;episodes:number;durationMin:number;durationMax:number};
type Theme={name:string;accent:string;background:string};
type SeasonGroup={number:number;entries:Anime[]};
type ConfigSnapshot={version:number;name:string;createdAt:string;favorites:number[];folders:Folder[];progress:Progress;tracked:Tracker[];theme:Theme;toolbar:ToolbarPosition;playerPrefs?:PlayerPrefs};
type ConfigProfile={id:string;name:string;snapshot:ConfigSnapshot};

const K={favorites:"animesoul:favorites",folders:"animesoul:folders",progress:"animesoul:progress-v2",tracked:"animesoul:tracked",theme:"animesoul:theme",toolbar:"animesoul:toolbar",playerPrefs:"animesoul:player-prefs",profiles:"animesoul:profiles",activeProfile:"animesoul:active-profile"};
const THEMES:Theme[]=[{name:"Аметист",accent:"#9a78ff",background:"#09080d"},{name:"Сакура",accent:"#f078aa",background:"#10090e"},{name:"Океан",accent:"#45b8cf",background:"#071014"},{name:"Манго",accent:"#f0a348",background:"#100d08"}];
const read=<T,>(key:string,fallback:T):T=>{if(typeof window==="undefined")return fallback;try{return JSON.parse(localStorage.getItem(key)??"") as T}catch{return fallback}};
const write=<T,>(key:string,value:T)=>localStorage.setItem(key,JSON.stringify(value));

export default function Home(){
 const[catalog,setCatalog]=useState<Anime[]>([]),[active,setActive]=useState<Anime|null>(null),[resumeRequested,setResumeRequested]=useState(false),[query,setQuery]=useState(""),[genre,setGenre]=useState("Все"),[offset,setOffset]=useState(0);
 const[loading,setLoading]=useState(true),[error,setError]=useState(""),[favorites,setFavorites]=useState<number[]>([]),[folders,setFolders]=useState<Folder[]>([]),[progress,setProgress]=useState<Progress>({});
 const[tracked,setTracked]=useState<Tracker[]>([]),[libraryOpen,setLibraryOpen]=useState(false),[folderPicker,setFolderPicker]=useState<Anime|null>(null),[openedFolder,setOpenedFolder]=useState<Folder|null>(null);
 const[sort,setSort]=useState("rating-desc"),[yearFrom,setYearFrom]=useState(""),[yearTo,setYearTo]=useState(""),[theme,setTheme]=useState(THEMES[0]);
 const[randomOpen,setRandomOpen]=useState(false),[randomGenre,setRandomGenre]=useState("Все"),[randomYearFrom,setRandomYearFrom]=useState(""),[randomYearTo,setRandomYearTo]=useState(""),[randomRating,setRandomRating]=useState("0");
 const[playerPrefs,setPlayerPrefs]=useState<PlayerPrefs>({autoSkipOpening:false,autoSkipEnding:false,autoNext:true,autoPlayResume:true}),[cardMeta,setCardMeta]=useState<Record<number,CardMeta>>({});
 const[profiles,setProfiles]=useState<ConfigProfile[]>([]),[activeProfile,setActiveProfile]=useState("default");
 useEffect(()=>{const loadedFavorites=read<number[]>(K.favorites,[]),loadedFolders=read<Folder[]>(K.folders,[]),loadedProgress=read<Progress>(K.progress,{}),loadedTracked=read<Tracker[]>(K.tracked,[]),loadedTheme=read<Theme>(K.theme,THEMES[0]),loadedToolbar=read<ToolbarPosition>(K.toolbar,"bottom"),active=localStorage.getItem(K.activeProfile)??"default";let loadedProfiles=read<ConfigProfile[]>(K.profiles,[]);if(active==="default"&&!loadedProfiles.some(p=>p.id==="default")){loadedProfiles=[{id:"default",name:"Основной",snapshot:{version:1,name:"Основной",createdAt:new Date().toISOString(),favorites:loadedFavorites,folders:loadedFolders,progress:loadedProgress,tracked:loadedTracked,theme:loadedTheme,toolbar:loadedToolbar}},...loadedProfiles];write(K.profiles,loadedProfiles)}setFavorites(loadedFavorites);setFolders(loadedFolders);setProgress(loadedProgress);setTracked(loadedTracked);setTheme(loadedTheme);setProfiles(loadedProfiles);setActiveProfile(active)},[]);
 useEffect(()=>{document.documentElement.style.setProperty("--accent",theme.accent);document.documentElement.style.setProperty("--accent-soft",`${theme.accent}33`);document.documentElement.style.setProperty("--bg",theme.background);document.body.style.backgroundColor=theme.background;write(K.theme,theme)},[theme]);
 useEffect(()=>setPlayerPrefs(current=>({...current,...read<Partial<PlayerPrefs>>(K.playerPrefs,{})})),[]);
 const load=async(next=0,append=false,q=query)=>{setLoading(true);setError("");try{const r=await fetch(`/api/yummy?mode=catalog&limit=24&offset=${next}&q=${encodeURIComponent(q)}`),p=await r.json();if(!r.ok)throw Error(p.error);setCatalog(c=>append?[...new Map([...c,...p.anime].map(a=>[a.anime_id,a])).values()]:p.anime);setOffset(next)}catch(e){setError(e instanceof Error?e.message:"Ошибка каталога")}finally{setLoading(false)}};
 useEffect(()=>{void load(0,false,"")},[]);
 const storedIds=useMemo(()=>Array.from(new Set([...favorites,...folders.flatMap(f=>f.animeIds)])),[favorites,folders]);
 useEffect(()=>{const missing=storedIds.filter(id=>!catalog.some(a=>a.anime_id===id));if(!missing.length)return;fetch(`/api/yummy?mode=details&ids=${missing.join(",")}`).then(r=>r.json()).then(p=>setCatalog(current=>[...current,...((p.anime??[]) as Anime[]).filter(a=>!current.some(x=>x.anime_id===a.anime_id))])).catch(()=>{})},[storedIds.join(","),catalog.length]);
 const idsNeedingStats=useMemo(()=>storedIds.filter(id=>!((progress[id]?.totalEpisodes??0)>0)),[storedIds,progress]);
 useEffect(()=>{if(!idsNeedingStats.length)return;let cancelled=false;(async()=>{const rows:(readonly[number,number,number])[]=[];for(const id of idsNeedingStats){if(cancelled)break;try{const r=await fetch(`/api/yummy?mode=videos&id=${id}`),p=await r.json();if(r.ok){const videos=p.videos as Video[],unique=[...new Map(videos.map(v=>[v.number,v])).values()];rows.push([id,unique.length,unique.reduce((sum,v)=>sum+(v.duration??0),0)])}}catch{}await new Promise(resolve=>setTimeout(resolve,180))}if(cancelled||!rows.length)return;setProgress(current=>{const next={...current};for(const[id,total,totalDuration]of rows)next[id]={episode:next[id]?.episode??"1",dub:next[id]?.dub??"",season:next[id]?.season??1,episodes:next[id]?.episodes??{},totalEpisodes:total,totalDuration};write(K.progress,next);return next})})();return()=>{cancelled=true}},[idsNeedingStats.join(",")]);
 useEffect(()=>{tracked.forEach(async item=>{try{const ids=item.animeIds?.length?item.animeIds:[item.animeId];let count=0;for(const id of ids){const r=await fetch(`/api/yummy?mode=videos&id=${id}`),p=await r.json();if(!r.ok)continue;const list=(p.videos as Video[]).filter(v=>!item.dubs?.length||item.dubs.includes(v.data.dubbing));count+=new Set(list.map(v=>v.number)).size;await new Promise(resolve=>setTimeout(resolve,150))}if(count>item.knownEpisodes){setTracked(current=>{const next=current.map(x=>x.animeId===item.animeId?{...x,newEpisodes:count-item.knownEpisodes}:x);write(K.tracked,next);return next})}}catch{}})},[tracked.length]);
 const saveFav=(v:number[])=>{setFavorites(v);write(K.favorites,v)},saveFolders=(v:Folder[])=>{setFolders(v);write(K.folders,v)},saveProgress=(v:Progress)=>{setProgress(v);write(K.progress,v)},saveTracked=(v:Tracker[])=>{setTracked(v);write(K.tracked,v)};
 const toggleFavorite=(id:number)=>saveFav(favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id]);
 const createFolder=()=>{const name=prompt("Название новой папки")?.trim();if(name){const next=[...folders,{id:crypto.randomUUID(),name,animeIds:[]}];saveFolders(next);return next.at(-1)}};
 const toggleFolder=(folder:Folder,id:number)=>saveFolders(folders.map(f=>f.id===folder.id?{...f,animeIds:f.animeIds.includes(id)?f.animeIds.filter(x=>x!==id):[...f.animeIds,id]}:f));
 const known=(id:number)=>catalog.find(a=>a.anime_id===id);
 const genres=useMemo(()=>["Все",...Array.from(new Set(catalog.flatMap(a=>a.genres?.map(g=>g.title)??[]))).slice(0,14)],[catalog]);
 const franchises=useMemo(()=>groupFranchises(catalog),[catalog]);
 const visible=useMemo(()=>franchises.filter(a=>(genre==="Все"||a.genres?.some(g=>g.title===genre))&&(!yearFrom||(a.year??0)>=+yearFrom)&&(!yearTo||(a.year??9999)<=+yearTo)).sort((a,b)=>sort==="rating-desc"?(b.rating?.average??0)-(a.rating?.average??0):sort==="rating-asc"?(a.rating?.average??0)-(b.rating?.average??0):sort==="year-desc"?(b.year??0)-(a.year??0):sort==="year-asc"?(a.year??0)-(b.year??0):(b.views??0)-(a.views??0)),[franchises,genre,yearFrom,yearTo,sort]);
 const randomCandidates=useMemo(()=>franchises.filter(a=>(randomGenre==="Все"||a.genres?.some(g=>g.title===randomGenre))&&(!randomYearFrom||(a.year??0)>=+randomYearFrom)&&(!randomYearTo||(a.year??9999)<=+randomYearTo)&&(a.rating?.average??0)>=+randomRating),[franchises,randomGenre,randomYearFrom,randomYearTo,randomRating]);
 useEffect(()=>{const targets=visible.slice(0,12).filter(a=>!cardMeta[a.anime_id]);if(!targets.length)return;let cancelled=false;(async()=>{for(const anime of targets){if(cancelled)break;try{const root=franchiseName(anime.title),familyResponse=await fetch(`/api/yummy?mode=catalog&limit=30&q=${encodeURIComponent(root)}`),familyPayload=await familyResponse.json(),family=((familyPayload.anime??[]) as Anime[]).filter(a=>franchiseName(a.title)===root&&/tv|тв|сериал/i.test(a.type?.name??"")),members=family.length?family:[anime],arcCount=new Set(members.map(a=>stripPart(a.title))).size,seasonCount=new Set(members.map(a=>a.season).filter((n):n is number=>typeof n==="number")).size,videoResponse=await fetch(`/api/yummy?mode=videos&id=${anime.anime_id}`),videoPayload=await videoResponse.json(),videos=(videoPayload.videos??[]) as Video[],unique=[...new Map(videos.map(v=>[v.number,v])).values()],durations=unique.map(v=>v.duration??0).filter(Boolean),meta:CardMeta={familyCount:Math.max(arcCount,seasonCount,members.length>1?2:1),episodes:unique.length,durationMin:durations.length?Math.min(...durations):0,durationMax:durations.length?Math.max(...durations):0};if(!cancelled)setCardMeta(current=>({...current,[anime.anime_id]:meta}))}catch{}await new Promise(resolve=>setTimeout(resolve,120))}})();return()=>{cancelled=true}},[visible.slice(0,12).map(a=>a.anime_id).join(","),cardMeta]);
 const last=useMemo(()=>Object.entries(progress).sort((a,b)=>Math.max(...Object.values(b[1].episodes).map(x=>x.updatedAt),0)-Math.max(...Object.values(a[1].episodes).map(x=>x.updatedAt),0))[0],[progress]);
 const lastAnime=last?known(+last[0]):undefined,lastState=last?.[1];
 const historyItems=useMemo(()=>Object.entries(progress).flatMap(([animeId,item])=>Object.entries(item.episodes).map(([key,state])=>{const[season,episode]=key.split(":");return{animeId:+animeId,season:+season||1,episode,state}})).sort((a,b)=>b.state.updatedAt-a.state.updatedAt).slice(0,30),[progress]);
 const animeProgress=(p?:AnimeProgress)=>{if(!p?.totalEpisodes)return 0;const watched=Object.values(p.episodes).filter(isEpisodeWatched).length;return Math.min(100,Math.round(watched/p.totalEpisodes*100))};
 const folderStats=(f:Folder)=>{const total=f.animeIds.reduce((sum,id)=>sum+(progress[id]?.totalEpisodes??0),0);const watched=f.animeIds.reduce((sum,id)=>sum+new Set(Object.entries(progress[id]?.episodes??{}).filter(([,e])=>isEpisodeWatched(e)).map(([key])=>key)).size,0);return{total,watched,percent:total?Math.min(100,Math.round(watched/total*100)):0}};
 const defaultPlayerPrefs:PlayerPrefs={autoSkipOpening:false,autoSkipEnding:false,autoNext:true,autoPlayResume:true};
 const makeSnapshot=(name:string):ConfigSnapshot=>({version:1,name,createdAt:new Date().toISOString(),favorites,folders,progress,tracked,theme,toolbar:read(K.toolbar,"bottom"),playerPrefs:{...defaultPlayerPrefs,...read<Partial<PlayerPrefs>>(K.playerPrefs,{})}});
 const exportConfig=()=>{const profileName=profiles.find(p=>p.id===activeProfile)?.name??"Основной";const blob=new Blob([JSON.stringify(makeSnapshot(profileName),null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`AnimeSoul-${profileName.replace(/[^\p{L}\p{N}-]+/gu,"-")}.json`;a.click();URL.revokeObjectURL(url)};
 const applySnapshot=(s:ConfigSnapshot)=>{write(K.favorites,s.favorites??[]);write(K.folders,s.folders??[]);write(K.progress,s.progress??{});write(K.tracked,s.tracked??[]);write(K.theme,s.theme??THEMES[0]);write(K.toolbar,s.toolbar??"bottom");write(K.playerPrefs,{...defaultPlayerPrefs,...s.playerPrefs})};
 const switchProfile=(id:string)=>{if(id===activeProfile)return;const currentName=profiles.find(p=>p.id===activeProfile)?.name??(activeProfile==="default"?"Основной":"Профиль"),savedCurrent={id:activeProfile,name:currentName,snapshot:makeSnapshot(currentName)};const updated=[...profiles.filter(p=>p.id!==activeProfile),savedCurrent];const target=updated.find(p=>p.id===id);if(!target){alert("Этот профиль не найден. Импортируй его заново.");return}write(K.profiles,updated);localStorage.setItem(K.activeProfile,id);applySnapshot(target.snapshot);location.reload()};
 const importConfig=async(file:File)=>{try{const parsed=JSON.parse(await file.text()) as ConfigSnapshot;if(!parsed||!Array.isArray(parsed.folders)||!parsed.progress)throw Error();const name=prompt("Название импортированного профиля",parsed.name||file.name.replace(/\.json$/i,""))?.trim();if(!name)return;const currentName=profiles.find(p=>p.id===activeProfile)?.name??(activeProfile==="default"?"Основной":"Профиль"),currentProfile={id:activeProfile,name:currentName,snapshot:makeSnapshot(currentName)},profile={id:crypto.randomUUID(),name,snapshot:{...parsed,name}},next=[...profiles.filter(p=>p.id!==activeProfile),currentProfile,profile];setProfiles(next);write(K.profiles,next);if(confirm(`Профиль «${name}» загружен. Переключиться на него сейчас?`)){localStorage.setItem(K.activeProfile,profile.id);applySnapshot(profile.snapshot);location.reload()}}catch{alert("Не удалось загрузить конфигурацию AnimeSoul")}};
 const openAnime=(anime:Anime,resume=false)=>{setResumeRequested(resume);setActive(anime)};
 const openLibrary=()=>{setActive(null);setResumeRequested(false);setLibraryOpen(true);setTimeout(()=>document.getElementById("my-library")?.scrollIntoView({behavior:"smooth"}),0)};
 if(active){const activeTracker=tracked.find(t=>t.animeId===active.anime_id||t.animeIds?.includes(active.anime_id));return <Watch anime={active} resumeRequested={resumeRequested} favorite={favorites.includes(active.anime_id)} onFavorite={()=>toggleFavorite(active.anime_id)} onBack={()=>{setActive(null);setResumeRequested(false)}} onLibrary={openLibrary} saved={progress[active.anime_id]} onProgress={v=>saveProgress({...progress,[active.anime_id]:v})} onFolders={()=>setFolderPicker(active)} tracker={activeTracker} onTrack={(count,dubs,animeIds,title)=>saveTracked([...tracked.filter(t=>t.animeId!==activeTracker?.animeId),{animeId:animeIds[0]??active.anime_id,animeIds,title,knownEpisodes:count,newEpisodes:0,dubs}])} onUntrack={()=>saveTracked(tracked.filter(t=>t.animeId!==activeTracker?.animeId))} folderPicker={folderPicker} folders={folders} toggleFolder={toggleFolder} createFolder={createFolder} closePicker={()=>setFolderPicker(null)}/>}
 return <main className="app"><Header query={query} setQuery={setQuery} onSearch={()=>void load(0,false,query)} onCatalog={()=>document.getElementById("catalog")?.scrollIntoView({behavior:"smooth"})} onLibrary={openLibrary} theme={theme} setTheme={setTheme} suggestions={franchises.filter(a=>query.length>1&&a.title.toLowerCase().includes(query.toLowerCase())).slice(0,6)} onSuggestion={a=>{setQuery(a.title);setActive(a)}} profiles={profiles} activeProfile={activeProfile} onSwitchProfile={switchProfile} onExport={exportConfig} onImport={importConfig}/>
  <section className="hero dashboard-hero"><div className="hero-content"><span className="eyebrow">ПРОДОЛЖИТЬ ПРОСМОТР</span>{lastAnime&&lastState?<><h1>{lastAnime.title}</h1><p>Серия {lastState.episode} · остановились на {formatTime(lastState.episodes[`${lastState.season??1}:${lastState.episode}`]?.position??0)}</p><button className="primary" onClick={()=>openAnime(lastAnime,true)}>▶ Продолжить просмотр</button></>:<><h1>Твоя коллекция.<br/><i>Твои правила.</i></h1><p>Начни смотреть аниме — последнее появится здесь.</p></>}<Toggle label="Автоматически запускать продолжение" value={playerPrefs.autoPlayResume} onChange={v=>{const next={...playerPrefs,autoPlayResume:v};setPlayerPrefs(next);write(K.playerPrefs,next)}}/></div>
   <div className="hero-widgets"><div className="hero-box"><h3>♥ Избранное <span>{favorites.length}</span></h3><div className="mini-list">{favorites.slice(0,3).map(id=><button key={id} onClick={()=>known(id)&&setActive(known(id)!)}>{known(id)?.title??`Аниме #${id}`}<small>{animeProgress(progress[id])}%</small></button>)}</div></div>
    <div className="hero-box"><h3>Папки <button onClick={createFolder}>＋</button></h3>{folders.slice(0,3).map(f=>{const s=folderStats(f);return <button className="folder-progress" key={f.id} onClick={()=>setOpenedFolder(f)}><span>{f.name}<small>{s.watched}/{s.total} серий</small></span><i><b style={{width:`${s.percent}%`}}/></i><em>{s.percent}%</em></button>})}</div>
    <div className="hero-box alerts"><h3>Отслеживаю <span>{tracked.length}</span></h3>{tracked.slice(0,4).map(t=><div className="hero-track" key={t.animeId}><button onClick={()=>known(t.animeId)&&setActive(known(t.animeId)!)}><span>{t.title}<small>{t.dubs?.length?t.dubs.join(", "):"Все озвучки"}</small><em className={t.newEpisodes>0?"release-status new":"release-status quiet"}><i/>{t.newEpisodes>0?`Новая серия · +${t.newEpisodes}`:"Новых серий нет"}</em></span>{t.newEpisodes>0&&<b>+{t.newEpisodes}</b>}</button><button className="untrack" title="Отписаться" onClick={()=>saveTracked(tracked.filter(x=>x.animeId!==t.animeId))}>×</button></div>)}{!tracked.length&&<small>Подписок пока нет</small>}</div></div>
  </section>
  <section className="library" id="my-library"><div className="section-head"><div><span className="eyebrow">МОЯ БИБЛИОТЕКА</span><h2>Папки и избранное</h2></div><button className="outline" onClick={createFolder}>＋ Новая папка</button></div>
   <div className="collection-grid"><div className="collection-card favorites-card"><h3>♥ Избранное</h3><b>{favorites.length} тайтлов · перетащи для сортировки</b><div>{favorites.map(id=><button draggable key={id} onDragStart={e=>e.dataTransfer.setData("text/plain",String(id))} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const from=Number(e.dataTransfer.getData("text/plain"));saveFav(reorder(favorites,from,id))}} onClick={()=>known(id)&&setActive(known(id)!)}><i>⠿</i>{known(id)?.title??`Аниме #${id}`}<span>{animeProgress(progress[id])}%</span></button>)}</div></div>{folders.map(f=>{const s=folderStats(f);return <div className="collection-card" key={f.id} role="button" tabIndex={0} onClick={()=>setOpenedFolder(f)}><h3>{f.name}</h3><b>{f.animeIds.length} тайтлов · {s.watched} из {s.total} серий</b><div className="wide-progress"><i style={{width:`${s.percent}%`}}/></div><div>{f.animeIds.slice(0,4).map(id=><button key={id}>{known(id)?.title??`Аниме #${id}`}</button>)}</div></div>})}</div>
   <div className="tracking-section"><div className="section-head"><div><span className="eyebrow">НОВЫЕ СЕРИИ</span><h2>Мои отслеживания</h2></div><span>{tracked.length} подписок</span></div><div className="tracking-list">{tracked.map(t=>{const a=known(t.animeId);return <article key={t.animeId}>{a?.poster?.big&&<img src={a.poster.big} alt=""/>}<button className="tracking-main" onClick={()=>a&&setActive(a)}><b>{t.title}</b><small>{t.dubs?.length?`Озвучки: ${t.dubs.join(", ")}`:"Все озвучки"}</small><span>{t.knownEpisodes} известных серий{t.newEpisodes>0&&<em> · +{t.newEpisodes} новых</em>}</span></button><div className="tracking-actions"><button className="untrack-button" onClick={()=>saveTracked(tracked.filter(x=>x.animeId!==t.animeId))}>Отписаться</button><span className={t.newEpisodes>0?"release-status new":"release-status quiet"}><i/>{t.newEpisodes>0?"Новая серия":"Новых серий нет"}</span></div></article>})}{!tracked.length&&<div className="empty">На странице аниме нажми «Следить за сериями», чтобы оно появилось здесь.</div>}</div></div>
   <div className="history-section"><div className="section-head"><div><span className="eyebrow">НЕДАВНО СМОТРЕЛИ</span><h2>История просмотра</h2></div><span>{historyItems.length} записей</span></div><div className="history-list">{historyItems.map(item=>{const anime=known(item.animeId);return <article key={`${item.animeId}:${item.season}:${item.episode}`}><button onClick={()=>{if(!anime)return;const current=progress[item.animeId];saveProgress({...progress,[item.animeId]:{...current,season:item.season,episode:item.episode}});openAnime(anime,true)}}>{anime?.poster?.big&&<img src={anime.poster.big} alt=""/>}<span><b>{anime?.title??`Аниме #${item.animeId}`}</b><small>Сезон {item.season} · серия {item.episode} · {formatTime(item.state.position)}</small></span><time>{new Date(item.state.updatedAt).toLocaleDateString("ru-RU",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"})}</time><em>▶ Продолжить</em></button></article>})}{!historyItems.length&&<div className="empty">История появится после начала просмотра первой серии.</div>}</div></div>
  </section>
  <section className="library" id="catalog"><div className="section-head"><div><span className="eyebrow">КАТАЛОГ YUMMYANIME</span><h2>{query?`Результаты: ${query}`:"Все аниме"}</h2></div></div>
   <div className="filter-panel"><select value={sort} onChange={e=>setSort(e.target.value)}><option value="rating-desc">Рейтинг: высокий</option><option value="rating-asc">Рейтинг: низкий</option><option value="year-desc">Сначала новые</option><option value="year-asc">Сначала старые</option><option value="views">По популярности</option></select><label>Год от <input type="number" value={yearFrom} onChange={e=>setYearFrom(e.target.value)} placeholder="1990"/></label><label>до <input type="number" value={yearTo} onChange={e=>setYearTo(e.target.value)} placeholder="2026"/></label><button onClick={()=>{setYearFrom("");setYearTo("");setSort("rating-desc");setGenre("Все")}}>Сбросить</button><button className="random-trigger" onClick={()=>setRandomOpen(v=>!v)}>⚄ Рандом</button></div>
   {randomOpen&&<div className="random-panel"><div><label>Жанр<select value={randomGenre} onChange={e=>setRandomGenre(e.target.value)}>{genres.map(g=><option key={g}>{g}</option>)}</select></label><label>Год от<input type="number" value={randomYearFrom} onChange={e=>setRandomYearFrom(e.target.value)} placeholder="1990"/></label><label>до<input type="number" value={randomYearTo} onChange={e=>setRandomYearTo(e.target.value)} placeholder="2026"/></label><label>Рейтинг от<select value={randomRating} onChange={e=>setRandomRating(e.target.value)}><option value="0">Любой</option><option value="6">6.0</option><option value="7">7.0</option><option value="8">8.0</option><option value="9">9.0</option></select></label></div><button className="primary" disabled={!randomCandidates.length} onClick={()=>{const picked=randomCandidates[Math.floor(Math.random()*randomCandidates.length)];if(picked)openAnime(picked)}}>⚄ Выбрать случайное аниме</button><small>{randomCandidates.length?`${randomCandidates.length} подходящих франшиз`:"Нет аниме с такими фильтрами"}</small></div>}
   <div className="genre-row">{genres.map(g=><button key={g} className={genre===g?"selected":""} onClick={()=>setGenre(g)}>{g}</button>)}</div>{error&&<div className="empty">{error}</div>}<div className="cards">{visible.map(a=><Card key={a.anime_id} anime={a} meta={cardMeta[a.anime_id]} onOpen={anime=>openAnime(anime)} favorite={favorites.includes(a.anime_id)} onFavorite={()=>toggleFavorite(a.anime_id)} onFolders={()=>setFolderPicker(a)} progress={progress[a.anime_id]}/>)}</div>{!query&&<button type="button" className="load-more" disabled={loading} onClick={()=>void load(offset+24,true,"")}>{loading?"Загружаем новые аниме…":"Показать ещё"}</button>}</section>
  <footer><Brand/><span>Видео и каталог: YummyAnime API</span><span>Все настройки хранятся локально</span></footer>
  {folderPicker&&<FolderPicker anime={folderPicker} folders={folders} onToggle={toggleFolder} onCreate={createFolder} onClose={()=>setFolderPicker(null)}/>}
  {openedFolder&&<FolderView folder={folders.find(f=>f.id===openedFolder.id)??openedFolder} known={known} progress={progress} onOpen={(a,resume)=>{setOpenedFolder(null);openAnime(a,resume)}} onNote={(id,note)=>saveFolders(folders.map(f=>f.id===openedFolder.id?{...f,notes:{...(f.notes??{}),[id]:note}}:f))} onReorder={(from,to)=>saveFolders(folders.map(f=>f.id===openedFolder.id?{...f,animeIds:reorder(f.animeIds,from,to)}:f))} onDelete={()=>{if(confirm(`Удалить папку «${openedFolder.name}»?`)){saveFolders(folders.filter(f=>f.id!==openedFolder.id));setOpenedFolder(null)}}} onClose={()=>setOpenedFolder(null)}/>}
  {libraryOpen&&<div className="toast">Библиотека открыта ниже</div>}</main>
}

function Watch({anime,resumeRequested,favorite,onFavorite,onBack,onLibrary,saved,onProgress,onFolders,tracker,onTrack,onUntrack,folderPicker,folders,toggleFolder,createFolder,closePicker}:{anime:Anime;resumeRequested:boolean;favorite:boolean;onFavorite:()=>void;onBack:()=>void;onLibrary:()=>void;saved?:AnimeProgress;onProgress:(v:AnimeProgress)=>void;onFolders:()=>void;tracker?:Tracker;onTrack:(n:number,d:string[],ids:number[],title:string)=>void;onUntrack:()=>void;folderPicker:Anime|null;folders:Folder[];toggleFolder:(f:Folder,id:number)=>void;createFolder:()=>unknown;closePicker:()=>void}){
 const initialPrefs={autoSkipOpening:false,autoSkipEnding:false,autoNext:true,autoPlayResume:true,...read<Partial<PlayerPrefs>>(K.playerPrefs,{})};
 const[dub,setDub]=useState(saved?.dub??""),[episode,setEpisode]=useState(saved?.episode??"1"),[player,setPlayer]=useState(""),[autoNext,setAutoNextState]=useState(initialPrefs.autoNext),[autoSkip,setAutoSkipState]=useState(initialPrefs.autoSkipOpening),[autoSkipEnding,setAutoSkipEndingState]=useState(initialPrefs.autoSkipEnding),[autoPlayResume,setAutoPlayResumeState]=useState(initialPrefs.autoPlayResume),[status,setStatus]=useState("Загружаем серии…"),[position,setPosition]=useState<ToolbarPosition>(read(K.toolbar,"bottom")), [autoPlay,setAutoPlay]=useState(false),[seasons,setSeasons]=useState<SeasonGroup[]>([{number:1,entries:[anime]}]),[selectedSeason,setSelectedSeason]=useState(saved?.season??1),[seasonVideos,setSeasonVideos]=useState<Record<number,Video[]>>({}),[trackOpen,setTrackOpen]=useState(false),[trackDubs,setTrackDubs]=useState<string[]>(tracker?.dubs??[]);
 const iframe=useRef<HTMLIFrameElement>(null);
 const familyRoot=useMemo(()=>franchiseName(anime.title),[anime.title]);
 const base=useMemo(()=>stripPart(anime.title),[anime.title]);
 useEffect(()=>{fetch(`/api/yummy?mode=catalog&limit=30&q=${encodeURIComponent(familyRoot)}`).then(r=>r.json()).then(p=>{const candidates=((p.anime as Anime[]??[]).filter(a=>franchiseName(a.title)===familyRoot&&/tv|тв|сериал/i.test(a.type?.name??"")));const source=candidates.length?candidates:[anime];const arcs=new Map<string,Anime[]>();for(const item of source){const arc=stripPart(item.title);arcs.set(arc,[...(arcs.get(arc)??[]),item])}const groups=[...arcs.entries()].sort(([,a],[,b])=>(Math.min(...a.map(x=>x.year??9999))-Math.min(...b.map(x=>x.year??9999)))||(Math.min(...a.map(x=>x.anime_id))-Math.min(...b.map(x=>x.anime_id)))).map(([,entries],index)=>({number:index+1,entries}));if(groups.length){setSeasons(groups);const savedSeason=saved?.season;const selected=savedSeason&&groups.some(g=>g.number===savedSeason)?savedSeason:groups.find(g=>g.entries.some(e=>e.anime_id===anime.anime_id))?.number??groups[0].number;setSelectedSeason(selected)}}).catch(()=>{})},[anime.anime_id,familyRoot]);
 const fetchVideos=async()=>{setStatus("Загружаем сезоны…");try{const loaded=await Promise.all(seasons.map(async group=>{const ordered=[...group.entries].sort((a,b)=>partNumber(a.title)-partNumber(b.title));const payloads=await Promise.all(ordered.map(async entry=>{for(let attempt=0;attempt<2;attempt++){const r=await fetch(`/api/yummy?mode=videos&id=${entry.anime_id}`),p=await r.json();if(r.ok)return p.videos as Video[];if(attempt===0)await new Promise(resolve=>setTimeout(resolve,700))}return []}));let offset=0;const normalized=payloads.flatMap(list=>{const mapped=list.map(v=>({...v,number:String((Number(v.number)||1)+offset)}));offset+=new Set(list.map(v=>v.number)).size;return mapped});const unique=[...new Map(normalized.map(v=>[v.video_id,v])).values()];return [group.number,unique] as const}));const next=Object.fromEntries(loaded);setSeasonVideos(next);setStatus(Object.values(next).some((list:Video[])=>list.length)?"":"Видео временно не загрузились") }catch{setStatus("Не удалось загрузить серии")}};
 useEffect(()=>{void fetchVideos()},[seasons.map(s=>s.entries.map(e=>e.anime_id).join(",")).join("|")]);
 const videos=seasonVideos[selectedSeason]??[];
 useEffect(()=>{if(!videos.length)return;const valid=saved?.dub&&videos.some(v=>v.data.dubbing===saved.dub);const nextDub=valid?saved!.dub:videos[0].data.dubbing;setDub(nextDub);const nums=videos.filter(v=>v.data.dubbing===nextDub).map(v=>v.number);setEpisode(selectedSeason===(saved?.season??1)&&nums.includes(saved?.episode??"")?saved!.episode:nums.sort((a,b)=>+a-+b)[0]??"1");setPlayer("")},[selectedSeason,videos.length]);
 const dubs=Array.from(new Set(videos.map(v=>v.data.dubbing))),episodes=Array.from(new Set(videos.filter(v=>v.data.dubbing===dub).map(v=>v.number))).sort((a,b)=>+a-+b),sources=videos.filter(v=>v.data.dubbing===dub&&v.number===episode),players=Array.from(new Set(sources.map(v=>v.data.player))),current=sources.find(v=>v.data.player===player)??sources.find(v=>/kodik/i.test(v.data.player))??sources[0],openingEnd=current?.skips?.opening?current.skips.opening.time+current.skips.opening.length:0,endingStart=current?.skips?.ending?.time??0,endingEnd=current?.skips?.ending?current.skips.ending.time+current.skips.ending.length:(current?.duration??0);
 useEffect(()=>{if(!sources.length)return;const preferred=sources.find(v=>/kodik/i.test(v.data.player))?.data.player??sources[0].data.player;if(!sources.some(v=>v.data.player===player))setPlayer(preferred)},[dub,episode,sources.length]);
 const episodeKey=`${selectedSeason}:${episode}`;
 const uniqueFranchiseVideos=Object.entries(seasonVideos).flatMap(([season,list])=>[...new Map(list.map(v=>[`${season}:${v.number}`,v])).values()]),totalAcrossSeasons=uniqueFranchiseVideos.length,totalDurationAcrossSeasons=uniqueFranchiseVideos.reduce((sum,v)=>sum+(v.duration??0),0);
 const save=(time:number,duration:number,completed=false)=>{const percent=duration?Math.min(100,Math.round(time/duration*100)):saved?.episodes[episodeKey]?.percent??0;onProgress({episode,dub,season:selectedSeason,totalEpisodes:totalAcrossSeasons||episodes.length,totalDuration:totalDurationAcrossSeasons||saved?.totalDuration,episodes:{...(saved?.episodes??{}),[episodeKey]:{position:time,duration,percent,completed:completed||percent>=100||(endingStart>0&&time>=endingStart),updatedAt:Date.now()}}})};
 const command=(method:string,extra={})=>iframe.current?.contentWindow?.postMessage({key:"kodik_player_api",value:{method,...extra}},"*");
 useEffect(()=>{const fn=(event:MessageEvent)=>{let d=event.data;try{if(typeof d==="string")d=JSON.parse(d)}catch{return}const key=d?.key??d?.type,val=d?.value??d;if(key==="kodik_player_time_update"){const time=Number(val.time??val.currentTime??val),duration=Number(val.duration??current?.duration??0);if(Number.isFinite(time)){save(time,duration);if(autoSkip&&openingEnd&&time>=current!.skips!.opening!.time&&time<openingEnd)command("seek",{seconds:openingEnd});if(autoSkipEnding&&endingStart&&time>=endingStart&&time<endingEnd){save(endingStart,duration,true);command("seek",{seconds:endingEnd})}}}if(key==="kodik_player_video_ended"||key==="ended"){save(Number(current?.duration??0),Number(current?.duration??0),true);if(autoNext){const next=episodes[episodes.indexOf(episode)+1];if(next){setAutoPlay(true);setEpisode(next)}}}};window.addEventListener("message",fn);return()=>window.removeEventListener("message",fn)},[episode,dub,autoNext,autoSkip,autoSkipEnding,openingEnd,endingStart,endingEnd,current?.video_id,saved]);
 const loaded=()=>{const start=saved?.episodes[episodeKey]?.position??0;setTimeout(()=>{if(start>5)command("seek",{seconds:start});if(autoPlay||(resumeRequested&&autoPlayResume)){command("play");setAutoPlay(false)}},700)};
 const setToolbar=(p:ToolbarPosition)=>{setPosition(p);write(K.toolbar,p)};
 return <main className="app"><Header query="" setQuery={()=>{}} onSearch={()=>{}} onCatalog={onBack} onLibrary={onLibrary} compact/>
  <section className="watch-shell"><button className="back" onClick={onBack}>← Каталог</button><div className="watch-heading"><div><span className="eyebrow">СЕЗОН {selectedSeason} · СЕРИЯ {episode}</span><h1>{base}</h1></div><b>★ {anime.rating?.average?.toFixed(1)??"—"}</b></div><div className="season-tabs">{seasons.map(s=><button className={s.number===selectedSeason?"active":""} key={s.number} onClick={()=>setSelectedSeason(s.number)}>Сезон {s.number}</button>)}</div><div className={`video-layout toolbar-${position}`}><div className="player-frame">{current&&<iframe ref={iframe} key={current.video_id} src={current.iframe_url} onLoad={loaded} title={`${base}, серия ${episode}`} allow="autoplay; fullscreen; picture-in-picture" allowFullScreen/>}{status&&<div className="player-status"><span>{status}</span>{!current&&!status.includes("Загружаем")&&<button onClick={()=>void fetchVideos()}>Повторить загрузку</button>}</div>}</div>
   <div className="player-toolbar"><label>Озвучка<select value={dub} onChange={e=>{setDub(e.target.value);setEpisode(videos.find(v=>v.data.dubbing===e.target.value)?.number??"1");setPlayer("")}}>{dubs.map(x=><option key={x}>{x}</option>)}</select></label><label>Серия<select value={episode} onChange={e=>{setEpisode(e.target.value);setPlayer("")}}>{episodes.map(x=><option key={x}>{isEpisodeWatched(saved?.episodes[`${selectedSeason}:${x}`])?"✓ ":""}{x}</option>)}</select></label><label>Источник<select value={current?.data.player??player} onChange={e=>setPlayer(e.target.value)}>{players.map(x=><option key={x}>{x}</option>)}</select></label>{openingEnd>0&&<button onClick={()=>command("seek",{seconds:openingEnd})}>Пропустить опенинг → {formatTime(openingEnd)}</button>}{endingStart>0&&<button onClick={()=>{save(endingStart,current?.duration??0,true);command("seek",{seconds:endingEnd})}}>Пропустить эндинг → {formatTime(endingEnd)}</button>}<Toggle label="Автоскип опенинга" value={autoSkip} onChange={v=>{setAutoSkipState(v);write(K.playerPrefs,{autoSkipOpening:v,autoSkipEnding,autoNext,autoPlayResume})}}/><Toggle label="Автоскип эндинга" value={autoSkipEnding} onChange={v=>{setAutoSkipEndingState(v);write(K.playerPrefs,{autoSkipOpening:autoSkip,autoSkipEnding:v,autoNext,autoPlayResume})}}/><Toggle label="Автосерия" value={autoNext} onChange={v=>{setAutoNextState(v);write(K.playerPrefs,{autoSkipOpening:autoSkip,autoSkipEnding,autoNext:v,autoPlayResume})}}/><label>Панель<select value={position} onChange={e=>setToolbar(e.target.value as ToolbarPosition)}><option value="bottom">Снизу</option><option value="top">Сверху</option><option value="left">Слева</option><option value="right">Справа</option></select></label></div></div>
   <div className="watch-info"><div><div className="tags">{anime.genres?.slice(0,8).map(g=><span key={g.alias}>{g.title}</span>)}</div><p>{anime.description}</p><div className="facts"><span>{seasons.length>1?"◆ Франшиза · сезоны собраны":"◇ Отдельный тайтл · страницы раздельно"}</span><span>{seasons.length} сезонов</span><span>{totalAcrossSeasons} серий всего</span><span>{durationRange(Object.values(seasonVideos).flat())}</span></div></div><aside><button onClick={onFavorite}>{favorite?"♥ В избранном":"♡ В избранное"}</button><button onClick={onFolders}>＋ Добавить в папку</button><button onClick={()=>setTrackOpen(!trackOpen)}>{tracker?"◉ Настроить отслеживание":"◎ Следить за франшизой"}</button>{trackOpen&&<div className="track-settings"><b>Озвучки всей франшизы</b><label><input type="checkbox" checked={!trackDubs.length} onChange={()=>setTrackDubs([])}/> Все озвучки</label>{dubs.map(d=><label key={d}><input type="checkbox" checked={trackDubs.includes(d)} onChange={()=>setTrackDubs(v=>v.includes(d)?v.filter(x=>x!==d):[...v,d])}/>{d}</label>)}<button onClick={()=>{onTrack(totalAcrossSeasons,trackDubs,seasons.flatMap(s=>s.entries.map(e=>e.anime_id)),familyRoot);setTrackOpen(false)}}>Сохранить</button>{tracker&&<button className="danger" onClick={onUntrack}>Отключить</button>}</div>}<button className="danger" onClick={()=>{if(confirm("Обнулить весь прогресс этого аниме?"))onProgress({episode:"1",dub,season:1,totalEpisodes:totalAcrossSeasons,totalDuration:totalDurationAcrossSeasons,episodes:{}})}}>↺ Обнулить прогресс</button></aside></div>
   <div className="all-seasons">{seasons.map(group=>{const list=seasonVideos[group.number]??[],nums=Array.from(new Set(list.map(v=>v.number))).sort((a,b)=>+a-+b),watched=nums.filter(e=>isEpisodeWatched(saved?.episodes[`${group.number}:${e}`])).length;return <section className="season-panel" key={group.number}><div><h2>Сезон {group.number}</h2><span>{watched} из {nums.length} просмотрено</span></div><div className="season-progress"><i style={{width:`${nums.length?watched/nums.length*100:0}%`}}/></div><div className="episode-grid">{nums.map(e=>{const ep=saved?.episodes[`${group.number}:${e}`],isWatched=isEpisodeWatched(ep),isActive=group.number===selectedSeason&&e===episode;return <button className={`${isActive?"active ":""}${isWatched?"watched":""}`.trim()} key={e} onClick={()=>{setSelectedSeason(group.number);setEpisode(e)}}><b>{e}{isWatched&&<i>✓</i>}</b><span>Серия {e}<small>{isWatched?"Просмотрено":`${ep?.percent??0}% · ${formatTime(ep?.position??0)}`}</small></span></button>})}</div></section>})}</div>
  </section>{folderPicker&&<FolderPicker anime={folderPicker} folders={folders} onToggle={toggleFolder} onCreate={createFolder} onClose={closePicker}/>}</main>
}

function Card({anime,meta,onOpen,favorite,onFavorite,onFolders,progress}:{anime:Anime;meta?:CardMeta;onOpen:(a:Anime)=>void;favorite:boolean;onFavorite:()=>void;onFolders:()=>void;progress?:AnimeProgress}){const whole=watchTimeProgress(progress),isFranchise=(meta?.familyCount??anime.franchiseCount??0)>1,status=releaseStatus(anime),duration=meta?.durationMin?meta.durationMin===meta.durationMax?formatDuration(meta.durationMin):`${formatDuration(meta.durationMin)}–${formatDuration(meta.durationMax)}`:"";return <article className="anime-card"><div className="poster" onClick={()=>onOpen(anime)}>{anime.poster?.big&&<img src={anime.poster.big} alt="" loading="lazy"/>}<span className="rating">★ {anime.rating?.average?.toFixed(1)??"—"}</span><span className={`release-badge ${status.kind}`}><i/>{status.label}</span>{meta&&<span className={isFranchise?"franchise-badge grouped":"franchise-badge standalone"}>{isFranchise?`◆ Франшиза · ${meta.familyCount} сезона`:"◇ Отдельная страница"}</span>}<button className="play">▶</button><div className="card-actions"><button onClick={e=>{e.stopPropagation();onFavorite()}}>{favorite?"♥":"♡"}</button><button title="Добавить в папку" onClick={e=>{e.stopPropagation();onFolders()}}>＋</button></div></div><h3 onClick={()=>onOpen(anime)}>{anime.title}</h3><p>{anime.year??"—"} · {anime.type?.name??"Аниме"}{duration?` · ${duration}`:""}{meta?.episodes?` · ${meta.episodes} ${/фильм|movie/i.test(anime.type?.name??"")?"часть":"серий"}`:""}</p><div className="tagline">{anime.genres?.slice(0,3).map(g=><span key={g.alias}>{g.title}</span>)}</div>{progress&&<div className="card-progress"><i style={{width:`${whole}%`}}/><small>{whole}% всего времени</small></div>}</article>}
function FolderPicker({anime,folders,onToggle,onCreate,onClose}:{anime:Anime;folders:Folder[];onToggle:(f:Folder,id:number)=>void;onCreate:()=>unknown;onClose:()=>void}){return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal small" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={onClose}>×</button><h2>Папки</h2><p>Куда добавить «{anime.title}»?</p><div className="folder-checks">{folders.map(f=><label key={f.id}><input type="checkbox" checked={f.animeIds.includes(anime.anime_id)} onChange={()=>onToggle(f,anime.anime_id)}/><span>{f.name}</span><b>{f.animeIds.includes(anime.anime_id)?"Добавлено":"Добавить"}</b></label>)}{!folders.length&&<p>Сначала создай папку — например, «Смотреть вечером».</p>}</div><div className="modal-actions"><button className="outline" onClick={onCreate}>＋ Новая папка</button><button className="primary" onClick={onClose}>Готово</button></div></div></div>}
function FolderView({folder,known,progress,onOpen,onNote,onReorder,onDelete,onClose}:{folder:Folder;known:(id:number)=>Anime|undefined;progress:Progress;onOpen:(a:Anime,resume?:boolean)=>void;onNote:(id:number,note:string)=>void;onReorder:(from:number,to:number)=>void;onDelete:()=>void;onClose:()=>void}){return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal folder-view" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={onClose}>×</button><div className="folder-view-head"><div><span className="eyebrow">ПАПКА · ПЕРЕТАЩИ ДЛЯ СОРТИРОВКИ</span><h2>{folder.name}</h2></div><button className="danger outline" onClick={onDelete}>Удалить папку</button></div><div className="folder-anime-list">{folder.animeIds.map(id=>{const a=known(id),p=progress[id],state=p?.episodes[`${p.season??1}:${p.episode}`]??Object.values(p?.episodes??{}).sort((x,y)=>y.updatedAt-x.updatedAt)[0],whole=watchTimeProgress(p);return <article draggable onDragStart={e=>e.dataTransfer.setData("text/plain",String(id))} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();onReorder(Number(e.dataTransfer.getData("text/plain")),id)}} key={id}><span className="drag">⠿</span>{a?.poster?.big&&<img className="folder-anime-link" src={a.poster.big} alt="" onClick={()=>onOpen(a,false)}/>}<div><h3 className={a?"folder-anime-link":""} onClick={()=>a&&onOpen(a,false)}>{a?.title??`Загружаем аниме #${id}…`}</h3><p>{p?.totalEpisodes??"—"} серий · сезон {p?.season??1} · {whole}% всего</p><div className="wide-progress"><i style={{width:`${whole}%`}}/></div><textarea value={folder.notes?.[id]??""} onChange={e=>onNote(id,e.target.value)} placeholder="Своя заметка об аниме…"/></div><aside><small>Остановились: {formatTime(state?.position??0)}</small>{a&&<button className="primary" onClick={()=>onOpen(a,true)}>▶ Продолжить</button>}</aside></article>})}{!folder.animeIds.length&&<div className="empty">В этой папке пока нет аниме</div>}</div></div></div>}
function Header({query,setQuery,onSearch,onCatalog,onLibrary,theme,setTheme,compact=false,suggestions=[],onSuggestion,profiles=[],activeProfile="default",onSwitchProfile,onExport,onImport}:{query:string;setQuery:(v:string)=>void;onSearch:()=>void;onCatalog:()=>void;onLibrary:()=>void;theme?:Theme;setTheme?:(t:Theme)=>void;compact?:boolean;suggestions?:Anime[];onSuggestion?:(a:Anime)=>void;profiles?:ConfigProfile[];activeProfile?:string;onSwitchProfile?:(id:string)=>void;onExport?:()=>void;onImport?:(file:File)=>void}){return <header><Brand/><nav><button onClick={onCatalog}>Каталог</button><button onClick={onLibrary}>Моя библиотека</button></nav>{!compact&&<div className="search-wrap"><form className="header-search" onSubmit={e=>{e.preventDefault();onSearch()}}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Поиск…"/><button>⌕</button></form>{suggestions.length>0&&<div className="suggestions">{suggestions.map(a=><button key={a.anime_id} onClick={()=>onSuggestion?.(a)}>{a.poster?.big&&<img src={a.poster.big} alt=""/>}<span>{a.title}<small>{a.year} · ★ {a.rating?.average?.toFixed(1)}</small></span></button>)}</div>}</div>}{theme&&setTheme&&<div className="theme-palette"><label title="Основной цвет"><input type="color" value={theme.background} onChange={e=>setTheme({...theme,name:"Своя",background:e.target.value})}/></label><label title="Акцентный цвет"><input type="color" value={theme.accent} onChange={e=>setTheme({...theme,name:"Своя",accent:e.target.value})}/></label>{THEMES.map(t=><button key={t.name} title={t.name} style={{background:`linear-gradient(135deg,${t.background} 50%,${t.accent} 50%)`}} onClick={()=>setTheme(t)}/>)}</div>}{!compact&&onExport&&onImport&&<div className="config-tools"><select value={activeProfile} onChange={e=>onSwitchProfile?.(e.target.value)}><option value="default">Основной</option>{profiles.filter(p=>p.id!=="default").map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button title="Выгрузить конфиг" onClick={onExport}>⇩</button><label title="Загрузить конфиг">⇧<input type="file" accept=".json,application/json" onChange={e=>{const file=e.target.files?.[0];if(file)onImport(file);e.currentTarget.value=""}}/></label></div>}</header>}
function Brand(){return <button className="brand" onClick={()=>location.href="/"}><span>魂</span> AnimeSoul</button>}
function Toggle({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void}){return <label className="toggle-row"><button type="button" className={value?"toggle on":"toggle"} onClick={()=>onChange(!value)}><i/></button><span>{label}</span></label>}
function formatTime(s:number){return `${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,"0")}`}
function formatDuration(seconds:number){const minutes=Math.round(seconds/60);return minutes>=60?`${Math.floor(minutes/60)} ч ${minutes%60} мин`:`${minutes} мин`}
function isEpisodeWatched(state?:EpisodeState){return Boolean(state?.completed||state?.percent===100)}
function watchTimeProgress(progress?:AnimeProgress){if(!progress)return 0;const watched=Object.values(progress.episodes).reduce((sum,state)=>sum+(state.completed&&state.duration?state.duration:Math.min(state.position,state.duration||state.position)),0),knownDurations=Object.values(progress.episodes).map(state=>state.duration).filter(Boolean),average=knownDurations.length?knownDurations.reduce((a,b)=>a+b,0)/knownDurations.length:0,total=progress.totalDuration||average*(progress.totalEpisodes??0);return total?Math.min(100,Math.round(watched/total*100)):0}
function releaseStatus(anime:Anime){const raw=`${anime.anime_status?.alias??""} ${anime.anime_status?.title??""}`.toLowerCase();if(/ongoing|airing|онгоинг|выходит/.test(raw))return{label:"Сейчас выходит",kind:"airing"};if(/announce|planned|upcoming|анонс|заплан/.test(raw)||(anime.year??0)>new Date().getFullYear())return{label:"Запланировано",kind:"planned"};return{label:"Вышло",kind:"released"}}
function durationRange(videos:Video[]){const values=videos.map(v=>v.duration??0).filter(Boolean);if(!values.length)return "Длительность не указана";return `${formatTime(Math.min(...values))}–${formatTime(Math.max(...values))} серия`}
function reorder(items:number[],from:number,to:number){if(from===to||!items.includes(from)||!items.includes(to))return items;const next=items.filter(id=>id!==from),index=next.indexOf(to);next.splice(index,0,from);return next}
function stripPart(title:string){return title.replace(/\s*(?:\||\.|-)?\s*часть\s*\d+$/i,"").trim()}
function partNumber(title:string){return Number(title.match(/часть\s*(\d+)$/i)?.[1]??1)}
function franchiseName(title:string){return stripPart(title).split(":")[0].replace(/\s+(?:сезон|season)\s*\d+$/i,"").replace(/\s+[IVX]{1,5}$/i,"").trim()}
function groupFranchises(items:Anime[]){const groups=new Map<string,Anime[]>();for(const anime of items){const tv=/tv|тв|сериал/i.test(anime.type?.name??"");const key=tv?`tv:${franchiseName(anime.title).toLowerCase()}`:`id:${anime.anime_id}`;groups.set(key,[...(groups.get(key)??[]),anime])}return [...groups.values()].map(entries=>{const ordered=[...entries].sort((a,b)=>(a.year??9999)-(b.year??9999)||a.anime_id-b.anime_id),representative=ordered[0],ratings=entries.map(a=>a.rating?.average).filter((v):v is number=>typeof v==="number"),statusSource=entries.find(a=>releaseStatus(a).kind==="airing")??entries.find(a=>releaseStatus(a).kind==="planned")??representative;return{...representative,title:entries.length>1?franchiseName(representative.title):representative.title,franchiseCount:entries.length,franchiseEntries:entries,anime_status:statusSource.anime_status,rating:ratings.length?{average:Math.max(...ratings)}:representative.rating,views:entries.reduce((sum,a)=>sum+(a.views??0),0)}})}
