"""Validate bilingual guides/local links and regenerate the static API inventory.

Run from app: python tools/check_docs.py [--write-api]. No service imports, user
configuration, network calls or application data access are needed.
"""
from __future__ import annotations

import argparse
import ast
from pathlib import Path
import re
from urllib.parse import unquote

APP = Path(__file__).resolve().parents[1]
ROOT = APP.parent
DOCS = APP / "docs"
METHODS = {"get", "put", "post", "delete", "patch", "websocket"}


def code(value: str) -> str:
    return "`" + value.replace("|", "\\|").replace("\n", " ") + "`"


def api_inventory(russian: bool = False) -> str:
    routes = []
    models = []
    paths = [APP / "backend/app/main.py", *sorted((APP / "backend/app/api").glob("*.py"))]
    for path in paths:
        tree = ast.parse(path.read_text(encoding="utf-8-sig"))
        prefix = ""
        for node in tree.body:
            if isinstance(node, ast.Assign) and isinstance(node.value, ast.Call):
                if isinstance(node.value.func, ast.Name) and node.value.func.id == "APIRouter":
                    prefix = next((ast.literal_eval(k.value) for k in node.value.keywords if k.arg == "prefix"), "")
        source = "../" + path.relative_to(APP).as_posix()
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                for decorator in node.decorator_list:
                    if not isinstance(decorator, ast.Call) or not isinstance(decorator.func, ast.Attribute):
                        continue
                    method = decorator.func.attr
                    if method not in METHODS or not decorator.args:
                        continue
                    route = prefix + ast.literal_eval(decorator.args[0])
                    if route == "/{path:path}":
                        continue
                    annotation = ast.unparse(node.returns) if node.returns else "Any"
                    routes.append((route, "WS" if method == "websocket" else method.upper(), node.name, source, node.lineno, annotation))
            if isinstance(node, ast.ClassDef) and any(isinstance(b, ast.Name) and b.id == "BaseModel" for b in node.bases):
                fields = []
                for field in node.body:
                    if isinstance(field, ast.AnnAssign) and isinstance(field.target, ast.Name):
                        default = ast.unparse(field.value) if field.value else ("обязательное" if russian else "required")
                        fields.append((field.target.id, ast.unparse(field.annotation), default))
                models.append((node.name, source, node.lineno, fields))
    nav = "[English](API_SCHEMA.md) | [Русский](API_SCHEMA.ru.md)"
    title = "Маршруты и модели запросов из исходников" if russian else "Routes and request models from source"
    intro = (
        "Сгенерировано `tools/check_docs.py --write-api` без запуска приложения. Таблица включает все прикладные HTTP/WS-маршруты desktop. Watch Party и `/health` отключены на Android. Служебные `/docs`, `/redoc`, `/openapi.json`, статические файлы и SPA fallback не включены."
        if russian else
        "Generated by `tools/check_docs.py --write-api` without starting the application. Includes every desktop application HTTP/WS route. Watch Party and `/health` are disabled on Android. Framework `/docs`, `/redoc`, `/openapi.json`, static files and the SPA fallback are excluded."
    )
    note = (
        "Аннотации ответов взяты из Python; `dict`/`Any` не описывают полную форму JSON. Динамические ответы, потребители, ошибки и примеры: [справочник API](API_REFERENCE.ru.md). Для живой схемы запустите backend и откройте `/openapi.json`."
        if russian else
        "Return annotations come from Python; `dict`/`Any` do not specify the complete JSON shape. Dynamic responses, callers, errors and examples: [API reference](API_REFERENCE.md). Start the backend and open `/openapi.json` for the live schema."
    )
    headers = "| Метод | Путь | Python-обработчик | Аннотация ответа |" if russian else "| Method | Path | Python handler | Return annotation |"
    out = [nav, "", "# " + title, "", intro, "", note, "", f"**{len(routes)} {'маршрутов' if russian else 'routes'}**", "",
           headers, "| --- | --- | --- | --- |"]
    for route, method, name, source, line, annotation in sorted(routes):
        out.append(f"| {method} | {code(route)} | [{name}]({source}#L{line}) | {code(annotation)} |")
    out += ["", "## " + ("Модели тела запроса" if russian else "Request body models"), "",
            "`Field(...)`: " + ("ограничения Pydantic; отсутствие default означает обязательное поле." if russian else "Pydantic constraints; no default means a required field.")]
    for name, source, line, fields in models:
        headers = "| Поле | Тип | Default / ограничения |" if russian else "| Field | Type | Default / validation |"
        out += ["", f"### {name}", "", f"[{name}]({source}#L{line})", "", headers, "| --- | --- | --- |"]
        for name, annotation, default in fields:
            out.append(f"| {code(name)} | {code(annotation)} | {code(default)} |")
    return "\n".join(out) + "\n"


def guides() -> list[Path]:
    return [ROOT / "README.md", ROOT / "README.ru.md", *sorted(APP.glob("*.md")),
            *sorted(DOCS.glob("*.md")), *sorted((APP / "mobile").glob("*.md"))]


def check() -> list[str]:
    errors = []
    for path in guides():
        text = path.read_text(encoding="utf-8")
        sibling = path.with_name(path.name.replace(".ru.md", ".md") if path.name.endswith(".ru.md") else path.stem + ".ru.md")
        if not sibling.is_file():
            errors.append(f"Missing language pair: {sibling.relative_to(ROOT)}")
        if not text.startswith("[English](") or "[Русский](" not in text.splitlines()[0]:
            errors.append(f"Missing language navigation: {path.relative_to(ROOT)}")
        # Ignore fenced examples; validate inline Markdown and HTML image links.
        body = re.sub(r"```.*?```", "", text, flags=re.S)
        targets = re.findall(r"\]\(([^)]+)\)", body) + re.findall(r'<img\b[^>]*\bsrc="([^"]+)"', body)
        for target in targets:
            target = target.strip().strip("<>")
            if re.match(r"(?:[a-z][a-z0-9+.-]*:|#)", target, flags=re.I):
                continue
            target = unquote(target.split("#")[0])
            if target and not (path.parent / target).exists():
                errors.append(f"Broken link in {path.relative_to(ROOT)}: {target}")
    for russian in (False, True):
        path = DOCS / ("API_SCHEMA.ru.md" if russian else "API_SCHEMA.md")
        if not path.exists() or path.read_text(encoding="utf-8") != api_inventory(russian):
            errors.append(f"Stale API inventory: {path.relative_to(ROOT)}; run --write-api")
    return errors


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write-api", action="store_true")
    options = parser.parse_args()
    if options.write_api:
        for russian in (False, True):
            path = DOCS / ("API_SCHEMA.ru.md" if russian else "API_SCHEMA.md")
            path.write_text(api_inventory(russian), encoding="utf-8")
    errors = check()
    for error in errors:
        print(error)
    if not errors:
        print(f"Documentation OK: {len(guides())} Markdown files, language pairs, local links, complete API inventory.")
    return int(bool(errors))


if __name__ == "__main__":
    raise SystemExit(main())
